### ISSUE TITLE
If I try creating a VM my PC freezes

### ISSUE THREAD

**Issue by imadethisfor1page** [chironjit/single-gpu-passthrough#1]
When I did the VM part I put in all my PCI Host Devices except when I attempted to put all three in it immediately said I couldn’t have one of them enabled (My WIFI) so I removed it and now it froze on “Creating Domain”. 
Running Pop OS! (Kubuntu activated) CPU Ryzen 7 3700X GPU RTX 3070 TI MOBO B450-F Gaming

**Comment by chironjit** [comment]
You are facing this issue as your OS can't unbind your GPU due to the fact that IOMMU settings in b450 motherboards are generally borked (either because its not on a different IOMMU group or that the correct settings are not enabled on the bios or both). You can try using the ACS patch to see if it will help. The best tutorial for that is available on Bryan Steiner's guide (first link under credits).

**Comment by chironjit** [comment]
Additional notes:
In my experience playing around with a B450 motherboard, manufacturers sometimes do not expose the right settings in the bios (which means you can't change the settings and can't tell if they are enabled / disabled), or that the correct settings do not work even if enabled. I had both issues with my motherboard.

In general, you would expect that the main pcie x16 to have a separate IOMMU group -> I have found that this does not guarantee that unbinding the GPU would work on a b450.

I did not try the ACS patch on Pop OS, but I had it done on the same b450 motherboard when I moved it over to be used as a home NAS(using unRAID). I can confirm that worked. YMMV for regular Linux desktop OSs.

**Comment by imadethisfor1page** [comment]
Thanks!
